---
# tasks file for roles/proxy

- name: Run HTTPD
  docker_container:
    name: httpd
    image: guillaumelaville/tp-devops-cpe:http-server
    expose:
      - 80
      - 8080
    ports:
      - "80:80"
      - "8080:8080"
